baseURL = "https://chenyongda2018.github.io/"
languageCode = "zh-cn"
title = "Dada's blog"
theme = "charaka-hugo-theme"
copyright = "&copy; <a href=\"https://github.com/natarajmb\">Nataraj Basappa</a> 2018"
paginate = "10" # Number of elements per page in pagination
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "G-0YXVGRNW9S" # Enable Google Analytics by entering your tracking id

[params]

[params.highlight]
  style = "zenburn"

[[params.social]]
  url = "about.html"
  fa_icon = "fas fa-info" 

[[params.social]]
  url = "https://github.com/chenyongda2018"
  fa_icon = "fab fa-github"

[[params.social]]
  url = "https://www.linkedin.com/in/%E6%B0%B8%E8%BE%BE-%E9%99%88-1042ab184/"
  fa_icon = "fab fa-linkedin-in"

[[params.social]]
  url = "https://twitter.com/Yong_da_Chen"
  fa_icon = "fab fa-twitter"