baseURL = "https://chenyongda2018.github.io/"
languageCode = "zh-cn"
title = "Dada's blog"
theme = "hugo-ink"

# Number of elements per page in pagination
paginate = "10" 
# Enable comments by entering your Disqus shortname
disqusShortname = "" 
# Enable Google Analytics by entering your tracking id
googleAnalytics = "G-0YXVGRNW9S" 
copyright = "© Copyright notice"

pygmentsstyle = "solarized-light"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
# Number of characters to show in summary.
summaryLength = 20


[params]
	subtitle = "Android Developer."

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/chenyongda2018"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
