# https://github.com/adityatelange/hugo-PaperMod/wiki/Features
baseURL = "https://chenyongda2018.github.io/"
title = "Petrichor's blog"
languageCode = "en-us"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[outputs]
# necessary for search
home = ["HTML", "RSS", "JSON"] 

[minify]
disableXML = true
minifyOutput = true

[markup]
  [markup.tableOfContents]
    endLevel = 8
    startLevel = 1
  [markup.highlight]
    noClasses = false

[params]
env = "production"
title = "Petrichor's blog"
description = "Android developer blog"
keywords = [ "Android", "Java", "Blog", "Petrichor" ]
author = "Petrichor"
images = [ "/images/profile.jpg" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "newfav.png"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  safari_pinned_tab = "/safari-pinned-tab.svg"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Petrichor's blog"
  subtitle = "Android developer"
  imageUrl = "/images/profile.jpg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Profile"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my Android development blog"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/chenyongda2018"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = ""

  [[params.socialIcons]]
  name = "twitter"
  url = ""

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/chenyongda2018/chenyongda2018.github.io/tree/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]
  # Number of last posts that will be displayed in the sidebar - set to 0 or remove to hide this section


[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 30
