
baseURL = "https://chenyongda2018.github.io/"
languageCode = "zh-cn"
title = "Dada's blog"
theme = "vitae"
paginate = 5
enableRobotsTXT = true


copyright = "© Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    # Add pagetitle to homepage <title> tag
	#pagetitle = "All about static site generation"

	# Add a subtitle to your website
	subtitle = "Android developer."

    # Optional 80x80 avatar image.
	avatar = "img/avatar.jpg"

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
	# mainSections = ["post"]

    # Show reading time on a post
	readingTime = true




# Comments
[params.comments]
# Enable Comments with "true"
enabled = false

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
#engine = "disqus"

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/chenyongda2018"

#[[params.social]]
#name = "Email"
#icon = "fas fa-envelope"
#cmd = "mailto:cyyy_da@163.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "index.xml"